name: Deployment

concurrency:
  group: pré-production
  cancel-in-progress: true

on:
    push:
        branches:
        - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: pré-production
    steps:
      - name: Prepare SSH
        run: |
          apt-get update && apt-get install -y sshpass openssh-client
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy - Pull
        run: sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.DEPLOY_DIRECTORY }} && git pull origin main && /usr/bin/php8.2 /usr/local/bin/composer install --no-interaction && bin/console doctrine:migrations:migrate --no-interaction && yarn install && yarn build"
      - name: Clean
        run: |
          rm -rf ~/.ssh
          echo "Deployed!"
